version: '3'
services:
  app:
    build: ./app
    restart: always
    depends_on:
      - db
      - redis
      - nsqd
    ports:
      - 9000:9000
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=movieuser
      - POSTGRES_PASSWORD=moviepass
      - POSTGRES_DB=moviedb
  redis:
    image: redis:alpine